Loading Data

In [27]:
import pandas as pd

df_overview = pd.read_csv("all-task-1-overview.csv")
df_reviews = pd.read_csv("all-task-1-featured-reviews.csv")

print("Overview data:")
print(df_overview.columns)
print("%d entries, and %d attributes \n" %(df_overview.shape[0],df_overview.shape[1]))


print("Reviews data:")
print(df_reviews.columns)
print("%d entries, and %d attributes \n" %(df_reviews.shape[0],df_reviews.shape[1]))

# Example Analysis
avg_ratings = df_reviews.groupby("place_id")["rating"].mean()
print("Average ratings per place_id:")
print(avg_ratings)

Overview data:
Index(['place_id', 'name', 'description', 'is_spending_on_ads', 'reviews',
       'rating', 'competitors', 'website', 'phone', 'can_claim', 'owner_name',
       'owner_profile_link', 'featured_image', 'main_category', 'categories',
       'workday_timing', 'is_temporarily_closed', 'closed_on', 'address',
       'review_keywords', 'link', 'query'],
      dtype='object')
107 entries, and 22 attributes

Reviews data:
Index(['place_id', 'place_name', 'review_id', 'review_link', 'name',
       'reviewer_id', 'reviewer_profile', 'rating', 'review_text',
       'published_at', 'published_at_date', 'response_from_owner_text',
       'response_from_owner_ago', 'response_from_owner_date',
       'total_number_of_reviews_by_reviewer',
       'total_number_of_photos_by_reviewer', 'is_local_guide',
       'review_translated_text', 'response_from_owner_translated_text',
       'experience_details', 'review_photos'],
      dtype='object')
856 entries, and 21 attributes

Average ratings per place_id:
place_id
ChIJ-TA7dlRYwokRDQuMTOTQuYw    3.625
ChIJ1ziF2bZZwokRdPzw_rXIrqk    4.625
ChIJ27CKRHdZwokRAMnhRQri-bU    4.875
ChIJ3WRZYp1ZwokRI0GzAf4kCIQ    3.750
ChIJ3wIXdlVYwokRTigVOATI8WQ    2.875
                               ...
ChIJvz4F1JNZwokRN-_0V6iwxpY    4.125
ChIJw-9BIqJZwokRJHawGH7Y_kc    4.250
ChIJw0ol8QFbwokR6-65pS8JSDk    4.500
ChIJx0VRQa1ZwokRPWVY4a2Cm58    5.000
ChIJzea1Mv9ZwokRRlvADDTSu4k    4.875
Name: rating, Length: 107, dtype: float64

Merging Dataframe

In [25]:
data = pd.merge(df_overview, df_reviews, on="place_id", how="inner")
print("Merged data:")
print(data.info())
print(data.describe(include='all'))
print(data.isnull().sum())

Merged data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856 entries, 0 to 855
Data columns (total 42 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   place_id                             856 non-null    object
 1   name_x                               856 non-null    object
 2   description                          736 non-null    object
 3   is_spending_on_ads                   0 non-null      float64
 4   reviews                              856 non-null    int64
 5   rating_x                             856 non-null    float64
 6   competitors                          856 non-null    object
 7   website                              824 non-null    object
 8   phone                                680 non-null    object
 9   can_claim                            40 non-null     float64
 10  owner_name                           856 non-null    object
 11  owner_profile_link                   816 non-null    object
 12  featured_image                       848 non-null    object
 13  main_category                        856 non-null    object
 14  categories                           856 non-null    object
 15  workday_timing                       832 non-null    object
 16  is_temporarily_closed                0 non-null      float64
 17  closed_on                            856 non-null    object
 18  address                              856 non-null    object
 19  review_keywords                      848 non-null    object
 20  link                                 856 non-null    object
 21  query                                856 non-null    object
 22  place_name                           856 non-null    object
 23  review_id                            856 non-null    object
 24  review_link                          856 non-null    object
 25  name_y                               856 non-null    object
 26  reviewer_id                          856 non-null    object
 27  reviewer_profile                     856 non-null    object
 28  rating_y                             856 non-null    int64
 29  review_text                          853 non-null    object
 30  published_at                         856 non-null    object
 31  published_at_date                    856 non-null    object
 32  response_from_owner_text             185 non-null    object
 33  response_from_owner_ago              190 non-null    object
 34  response_from_owner_date             190 non-null    object
 35  total_number_of_reviews_by_reviewer  856 non-null    int64
 36  total_number_of_photos_by_reviewer   856 non-null    int64
 37  is_local_guide                       628 non-null    float64
 38  review_translated_text               362 non-null    object
 39  response_from_owner_translated_text  173 non-null    object
 40  experience_details                   856 non-null    object
 41  review_photos                        856 non-null    object
dtypes: float64(5), int64(4), object(33)
memory usage: 281.0+ KB
None
                           place_id     name_x  \
count                           856        856
unique                          107        107
top     ChIJ_1oyZaZZwokR1c-HIVJ3xzo  230 Fifth
freq                              8          8
mean                            NaN        NaN
std                             NaN        NaN
min                             NaN        NaN
25%                             NaN        NaN
50%                             NaN        NaN
75%                             NaN        NaN
max                             NaN        NaN

                                              description  is_spending_on_ads  \
count                                                 736                 0.0
unique                                                 92                 NaN
top     230 FIFTH is New York's largest outdoor Roofto...                 NaN
freq                                                    8                 NaN
mean                                                  NaN                 NaN
std                                                   NaN                 NaN
min                                                   NaN                 NaN
25%                                                   NaN                 NaN
50%                                                   NaN                 NaN
75%                                                   NaN                 NaN
max                                                   NaN                 NaN

             reviews    rating_x  \
count     856.000000  856.000000
unique           NaN         NaN
top              NaN         NaN
freq             NaN         NaN
mean     1269.084112    4.419626
std      2428.753100    0.192218
min         8.000000    3.500000
25%       347.000000    4.300000
50%       691.000000    4.400000
75%      1320.000000    4.600000
max     22461.000000    4.900000

                                              competitors  \
count                                                 856
unique                                                107
top     Name: Monarch Rooftop\nLink: https://www.googl...
freq                                                    8
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                              website            phone  can_claim  ...  \
count                             824              680       40.0  ...
unique                            101               85        NaN  ...
top     http://www.raineslawroom.com/  +1 212-725-4300        NaN  ...
freq                               16                8        NaN  ...
mean                              NaN              NaN        1.0  ...
std                               NaN              NaN        0.0  ...
min                               NaN              NaN        1.0  ...
25%                               NaN              NaN        1.0  ...
50%                               NaN              NaN        1.0  ...
75%                               NaN              NaN        1.0  ...
max                               NaN              NaN        1.0  ...

                                 response_from_owner_text  \
count                                                 185
unique                                                178
top     Thank you for your review! We hope you visit a...
freq                                                    5
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

       response_from_owner_ago response_from_owner_date  \
count                      190                      190
unique                      24                      190
top                Hace un ano      2024-10-19T22:20:07
freq                        27                        1
mean                       NaN                      NaN
std                        NaN                      NaN
min                        NaN                      NaN
25%                        NaN                      NaN
50%                        NaN                      NaN
75%                        NaN                      NaN
max                        NaN                      NaN

       total_number_of_reviews_by_reviewer total_number_of_photos_by_reviewer  \
count                           856.000000                         856.000000
unique                                 NaN                                NaN
top                                    NaN                                NaN
freq                                   NaN                                NaN
mean                            135.837617                         678.684579
std                             243.342419                        2547.245611
min                               1.000000                           0.000000
25%                              10.000000                           4.000000
50%                              52.500000                          43.000000
75%                             139.000000                         322.500000
max                            2363.000000                       42254.000000

       is_local_guide                             review_translated_text  \
count           628.0                                                362
unique            NaN                                                362
top               NaN  Los cocteles siempre son un exito aqui. Fuerte...
freq              NaN                                                  1
mean              1.0                                                NaN
std               0.0                                                NaN
min               1.0                                                NaN
25%               1.0                                                NaN
50%               1.0                                                NaN
75%               1.0                                                NaN
max               1.0                                                NaN

                      response_from_owner_translated_text experience_details  \
count                                                 173                856
unique                                                165                242
top     !Gracias por tu resena! Esperamos que nos visi...                 []
freq                                                    5                339
mean                                                  NaN                NaN
std                                                   NaN                NaN
min                                                   NaN                NaN
25%                                                   NaN                NaN
50%                                                   NaN                NaN
75%                                                   NaN                NaN
max                                                   NaN                NaN

       review_photos
count            856
unique           455
top               []
freq             402
mean             NaN
std              NaN
min              NaN
25%              NaN
50%              NaN
75%              NaN
max              NaN

[11 rows x 42 columns]
place_id                                 0
name_x                                   0
description                            120
is_spending_on_ads                     856
reviews                                  0
rating_x                                 0
competitors                              0
website                                 32
phone                                  176
can_claim                              816
owner_name                               0
owner_profile_link                      40
featured_image                           8
main_category                            0
categories                               0
workday_timing                          24
is_temporarily_closed                  856
closed_on                                0
address                                  0
review_keywords                          8
link                                     0
query                                    0
place_name                               0
review_id                                0
review_link                              0
name_y                                   0
reviewer_id                              0
reviewer_profile                         0
rating_y                                 0
review_text                              3
published_at                             0
published_at_date                        0
response_from_owner_text               671
response_from_owner_ago                666
response_from_owner_date               666
total_number_of_reviews_by_reviewer      0
total_number_of_photos_by_reviewer       0
is_local_guide                         228
review_translated_text                 494
response_from_owner_translated_text    683
experience_details                       0
review_photos                            0
dtype: int64

In [26]:
data

,place_id,name_x,description,is_spending_on_ads,reviews,rating_x,competitors,website,phone,can_claim,...,response_from_owner_text,response_from_owner_ago,response_from_owner_date,total_number_of_reviews_by_reviewer,total_number_of_photos_by_reviewer,is_local_guide,review_translated_text,response_from_owner_translated_text,experience_details,review_photos
0,ChIJ_1oyZaZZwokR1c-HIVJ3xzo,230 Fifth,230 FIFTH is New York's largest outdoor Roofto...,NaN,22461,4.3,Name: Monarch Rooftop\nLink: https://www.googl...,http://www.230-fifth.com/,+1 212-725-4300,NaN,...,NaN,NaN,NaN,152,279,1.0,NaN,NaN,"[{""name"":""Comida"",""value"":5},{""name"":""Servicio...","[{""id"":""AF1QipOQs8maHe6FB9js0LCFMNOGkJl72GVh8T..."
1,ChIJ_1oyZaZZwokR1c-HIVJ3xzo,230 Fifth,230 FIFTH is New York's largest outdoor Roofto...,NaN,22461,4.3,Name: Monarch Rooftop\nLink: https://www.googl...,http://www.230-fifth.com/,+1 212-725-4300,NaN,...,NaN,NaN,NaN,260,739,1.0,NaN,NaN,"[{""name"":""Precio por persona"",""value"":""50-100 ...","[{""id"":""AF1QipPmG_Yh0eFbClwCSyx2yik6SCWFyQYpxV..."
2,ChIJ_1oyZaZZwokR1c-HIVJ3xzo,230 Fifth,230 FIFTH is New York's largest outdoor Roofto...,NaN,22461,4.3,Name: Monarch Rooftop\nLink: https://www.googl...,http://www.230-fifth.com/,+1 212-725-4300,NaN,...,NaN,NaN,NaN,23,49,1.0,NaN,NaN,"[{""name"":""Precio por persona"",""value"":""Mas de ...","[{""id"":""AF1QipNtEe4695aiHZt8wb96dyXKbTTC9XM83n..."
3,ChIJ_1oyZaZZwokR1c-HIVJ3xzo,230 Fifth,230 FIFTH is New York's largest outdoor Roofto...,NaN,22461,4.3,Name: Monarch Rooftop\nLink: https://www.googl...,http://www.230-fifth.com/,+1 212-725-4300,NaN,...,NaN,NaN,NaN,123,419,1.0,NaN,NaN,"[{""name"":""Precio por persona"",""value"":""1-10 $""...","[{""id"":""AF1QipMtK_lNUnBq1UlhFCXVPY7UQ-_r7t8sPM..."
4,ChIJ_1oyZaZZwokR1c-HIVJ3xzo,230 Fifth,230 FIFTH is New York's largest outdoor Roofto...,NaN,22461,4.3,Name: Monarch Rooftop\nLink: https://www.googl...,http://www.230-fifth.com/,+1 212-725-4300,NaN,...,Thank you so much for your review,Hace 6 meses,2024-10-19T22:20:07,107,29,1.0,NaN,Muchas gracias por tu resena,"[{""name"":""Servicio"",""value"":5},{""name"":""Ambien...","[{""id"":""AF1QipMn9XiwSLjfASe7QNwQnLOyNPqZ5u1IJE..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,ChIJ1ziF2bZZwokRdPzw_rXIrqk,Bar Pendry Manhattan West,Bar Pendry is a classic cocktail emporium that...,NaN,8,4.6,Name: Patent Pending\nLink: https://www.google...,https://www.pendry.com/manhattan-west/dining/b...,+1 212-933-7000,NaN,...,NaN,NaN,NaN,3,0,NaN,Las bebidas y el servicio son de primera categ...,NaN,"[{""name"":""Servicio"",""value"":5},{""name"":""Ambien...",[]
852,ChIJ1ziF2bZZwokRdPzw_rXIrqk,Bar Pendry Manhattan West,Bar Pendry is a classic cocktail emporium that...,NaN,8,4.6,Name: Patent Pending\nLink: https://www.google...,https://www.pendry.com/manhattan-west/dining/b...,+1 212-933-7000,NaN,...,NaN,NaN,NaN,6,1,NaN,Excelente lugar. Recomendado.,NaN,"[{""name"":""Precio por persona"",""value"":""30-50 $...",[]
853,ChIJ1ziF2bZZwokRdPzw_rXIrqk,Bar Pendry Manhattan West,Bar Pendry is a classic cocktail emporium that...,NaN,8,4.6,Name: Patent Pending\nLink: https://www.google...,https://www.pendry.com/manhattan-west/dining/b...,+1 212-933-7000,NaN,...,NaN,NaN,NaN,7,43,1.0,NaN,NaN,"[{""name"":""Servicio"",""value"":5},{""name"":""Ambien...",[]
854,ChIJ1ziF2bZZwokRdPzw_rXIrqk,Bar Pendry Manhattan West,Bar Pendry is a classic cocktail emporium that...,NaN,8,4.6,Name: Patent Pending\nLink: https://www.google...,https://www.pendry.com/manhattan-west/dining/b...,+1 212-933-7000,NaN,...,NaN,NaN,NaN,148,3106,1.0,NaN,NaN,"[{""name"":""Precio por persona"",""value"":""20-30 $...",[]
855,ChIJ1ziF2bZZwokRdPzw_rXIrqk,Bar Pendry Manhattan West,Bar Pendry is a classic cocktail emporium that...,NaN,8,4.6,Name: Patent Pending\nLink: https://www.google...,https://www.pendry.com/manhattan-west/dining/b...,+1 212-933-7000,NaN,...,NaN,NaN,NaN,6,5,NaN,NaN,NaN,"[{""name"":""Precio por persona"",""value"":""20-30 $...",[]